services:
  apigateway:
     container_name: "apigateway"
     image: ${DOCKER_REGISTRY-}apigateway
     build:
       context: .
       dockerfile: ApiGateway/Dockerfile
     environment:
       - ASPNETCORE_ENVIRONMENT=Development
     ports:
       - "5000:8080"
     depends_on:
       - productservice
     links:
       - productservice
     networks:
       - net

  productservice:
    container_name: "productservice"
    image: ${DOCKER_REGISTRY-}productservice
    build:
      context: .
      dockerfile: ProductService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - CONNECTION_STRING=Server=productdb;Database=Products;User=root;Password=root;Port=3306 
    depends_on:
      - productdb 
    links:
      - productdb
    networks:
      - net

  productdb:
    container_name: "productdb"
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Products
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - productdb:/var/lib/mysql
    networks:
      - net

volumes:
  productdb:

networks:
  net:
